<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>NfmFileSystem</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileWalker\FileWalker.csproj" />
      <ProjectReference Include="..\nfzf\nfzf.csproj" />
      <ProjectReference Include="..\Ui.Core\Ui.Core.csproj" />
    </ItemGroup>

</Project>
