<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>nfm.ListWindows</AssemblyName>
        <RootNamespace>nfm.ListWindows</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ui.Core\Ui.Core.csproj" />
    </ItemGroup>

</Project>
