<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>WinExe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileSystem\FileSystem.csproj" />
      <ProjectReference Include="..\Win32Menu\Win32Menu.csproj" />
    </ItemGroup>

</Project>
